apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apollo
  namespace: default
spec:
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      nodeSelector:
        kubernetes.io/hostname: spi-mpic
      containers:
      - name: apollo
        image: docker.io/loulou3333444/fibonacci_bench@sha256:4c95ccbb0373d303e78c7c1b030efdb304b87c01d686bab672f1e769df13541b
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /dev/spidev.0
          name: spidev
      volumes:
      - name: spidev
        hostPath:
          path: /dev/spidev0.0
          type: CharDevice